### ISSUE TITLE
build out API in phoenix!

### ISSUE THREAD

**Issue by gcampo88** [PRX/jingle.prx.org#26]

**Comment by pkarman** [comment]
@gcampo88 is this still in  process? Or should it be moved to backlog? Re-assign to current Epic?

**Comment by gcampo88** [comment]
I've reassigned to current epic. This is likely too broad to be a single ticket -- may break it up into more specific directions during tomorrow' Adze planning meeting.

**Comment by gcampo88** [comment]
to be groomed tomorrow 8/29 in Adze planning meeting

**Comment by gcampo88** [comment]
This ticket is too broad -- going to rely on #32 and #36 to generate new, more specific tickets. Closing this.
