### ISSUE TITLE
change Adze name

### ISSUE THREAD

**Issue by gcampo88** [PRX/jingle.prx.org#33]

**Comment by gcampo88** [comment]
http://www.popularwoodworking.com/tools/woodworking-glossary

**Comment by kookster** [comment]
jig and jigsaw make me happy (also because a jig is a dance)

**Comment by kookster** [comment]
ok, `jingle.prx.org` for the API
and `sponsor.prx.org` for the UI, pending @farski review

**Comment by gcampo88** [comment]
update: no go on `sponsor.prx.org` for UI. @farski mulling options. most popular so far : `advise.prx.org`

**Comment by kookster** [comment]
Making a new ticket for the public name change
